#VERSION DOCKER COMPOSE
version: '3'
#SERVICIOS
#DEFINO LA BASE DE DATOS A UTILIZAR Y EL PUERTO A EXPONER 
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
#DEFINO EL SERVICIO DJANGO PARA EL BACKEND QUE DEPENDE DE LA BASE DE DATOS
  django:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: mysecretpassword
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: joseka
#SERVICIO FRONTEND QUE DEPENDE 
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:


