version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      DB_ENGINE: \${DB_ENGINE}
      DB_NAME: \${DB_NAME}
      DB_USER: \${DB_USER}
      DB_PASS: \${DB_PASS}
      DB_HOST: \${DB_HOST}
      DB_PORT: \${DB_PORT}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: \${DB_NAME}
      POSTGRES_USER: \${DB_USER}
      POSTGRES_PASSWORD: \${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

