name: Update index.html

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m 'Auto update index.html'
          git push
