name: Deploy Nginx 

on:
  push:
    branches: [ main ]
    
    paths: 
    - 'prueba-3/index.html'
    - 'prueba-3/Dockerfile'
   
     

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Disable BuildKit and build Docker image
      run: 
        export DOCKER_BUILDKIT=0
        export COMPOSE_DOCKER_CLI_BUILD=0
        docker build -t my-image .

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: prueba-tecnica/prueba-3/Dockerfile
        push: true
        tags: nginx-image:latest
        