name: Deploy Nginx 

on:
  push:
    branches: [ main ]
    paths: 
    - prueba-3/index.html
    
   
     
jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
 

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: /prueba-tecnica/prueba-3
        file: /prueba-tecnica/prueba-3/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-image:latest
