name: Deploy Nginx
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: josekademian/img-nginx-prueba:latest
      - name: Deploy to Docker Compose
        uses: docker/compose-action@v1.0.0-rc1
        with:
          compose-file: docker-compose.yml
          project-name: nginx
          service: web
          environment: |
            NGINX_PORT=80
          secrets: |
            DOCKERHUB_USERNAME= ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD= ${{ secrets.DOCKERHUB_TOKEN }}