name: Deploy Nginx 

on:
  push:
    branches: [ main ]
    paths: 
    - prueba-3/index.html
    - prueba-3/Dockerfile
   
     

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman buildah

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          sudo podman build -t nginx-image:latest -f ./prueba-3/Dockerfile .
          sudo podman login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          sudo podman push nginx-image:latest docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nginx-image:latest